/**
 * Loader options interface
 */
export interface LoaderOptions {
	camelCase?: boolean;
	quote?: "single" | "double";
	indentStyle?: "tab" | "space";
	indentSize?: number;
	mode?: "emit" | "verify";
	sort?: boolean;
	namedExport?: boolean;
	banner?: string;
}

/**
 * Export format marker interface
 */
export interface ExportMarker {
	pattern: string;
	isNamedExport: boolean;
}

/**
 * CSS module pattern interface
 */
export interface CssModulePatterns {
	OBJECT_EXPORT: RegExp;
	NAMED_EXPORT: RegExp;
	ALIASED_EXPORT: RegExp;
}

/**
 * JSON Schema property definition
 */
interface SchemaProperty {
	type: "boolean" | "string" | "number";
	enum?: string[];
}

/**
 * JSON Schema definition for validation
 */
interface SchemaDefinition {
	type: "object";
	properties: Record<string, SchemaProperty>;
	additionalProperties: boolean;
}

/**
 * Regular expressions for matching CSS module and style file extensions.
 */
export const STYLE_EXT_REGEX = /\.(css|postcss|pcss|scss|sass|less|styl|sss)$/;

/**
 * Schema for loader options validation.
 * Conforms to JSON Schema Draft-07 specification for use with schema-utils.
 */
export const SCHEMA: SchemaDefinition = {
	type: "object",
	properties: {
		camelCase: { type: "boolean" },
		quote: { type: "string", enum: ["single", "double"] },
		indentStyle: { type: "string", enum: ["tab", "space"] },
		indentSize: { type: "number" },
		mode: { type: "string", enum: ["emit", "verify"] },
		sort: { type: "boolean" },
		namedExport: { type: "boolean" },
		banner: { type: "string" }
	},
	additionalProperties: false
};

/**
 * Default options for the loader.
 */
export const DEFAULT_OPTIONS: Required<LoaderOptions> = {
	camelCase: false,
	quote: "double",
	indentStyle: "space",
	indentSize: 2,
	mode: "emit",
	sort: false,
	namedExport: true,
	banner: "// This file is automatically generated.\n// Please do not change this file!"
};

/**
 * Regular expressions for matching different CSS module export formats.
 */
export const CSS_MODULE_PATTERNS: CssModulePatterns = {
	OBJECT_EXPORT: /"([^"\\/;()\n]+)":/g,
	NAMED_EXPORT: /export (?:var|const) (\w+) =/g,
	// Matches aliased exports for JS keywords: export { _1 as "class" }
	ALIASED_EXPORT: /export\s*{\s*[_a-zA-Z0-9]+\s+as\s+"([^"\\]+)"\s*}/g
};

/**
 * Export format markers for different CSS loader versions.
 */
export const EXPORT_MARKERS: ExportMarker[] = [
	{ pattern: "___CSS_LOADER_EXPORT___.locals = {", isNamedExport: false },
	{ pattern: "export {", isNamedExport: true }, // Aliased exports for keywords
	{ pattern: "export var ", isNamedExport: true },
	{ pattern: "export const ", isNamedExport: true },
	{ pattern: "module.exports = {", isNamedExport: false },
	{ pattern: "exports.locals = {", isNamedExport: false }
];

/**
 * JavaScript reserved keywords that cannot be used as named exports.
 * Source: ECMAScript specification
 */
export const JS_KEYWORDS: Set<string> = new Set([
	// Keywords
	"break", "case", "catch", "class", "const", "continue", "debugger", "default",
	"delete", "do", "else", "export", "extends", "finally", "for", "function",
	"if", "import", "in", "instanceof", "new", "return", "super", "switch",
	"this", "throw", "try", "typeof", "var", "void", "while", "with", "yield",
	// Future reserved words
	"enum", "implements", "interface", "let", "package", "private", "protected",
	"public", "static", "await",
	// Strict mode reserved words
	"arguments", "eval",
	// Literals
	"null", "true", "false"
]);
